services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "80:80"   
    volumes:
      - ./template.plist:/usr/src/dist/template.plist
      - ./data/android:/usr/src/dist/android
      - ./data/ios:/usr/src/dist/ios
      - ./data/plist:/usr/src/dist/plist
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 3s
      retries: 10
